const SEARCH = 'SEARCH';
const GET_HISTORY = 'GET_HISTORY';
const SAVE_HISTORY = 'SAVE_HISTORY';
const SELECT_VIDEO = 'SELECT_VIDEO';

export {
  SEARCH,
  GET_HISTORY,
  SAVE_HISTORY,
  SELECT_VIDEO
};
